### ISSUE TITLE
Unable to install on Windows 2003 R2 SP2

### ISSUE THREAD

**Issue by frehnejc** [Azure/App-Service-Migration-Assistant#1]
#### Investigative information

- UTC Timestamp: 1/03/2019 11:48pm
- Migration Tool App version : 0.0.1.59773
- OS Version: 2003 R2 SP2 with all latest Updates.

#### Repro steps

1. Install MSI 
2. Error message on install: This installation package cannot be installed by the Windows Installer service. You must install a Windows service pack that contains a newer version of the Windows Installer service.
#### Expected behavior

After I perform step A, the installer should complete.

#### Actual behavior
Error on screen: 
This installation package cannot be installed by the Windows Installer service. You must install a Windows service pack that contains a newer version of the Windows Installer service.
#### Known workarounds

Nil available.

**Comment by krolson** [comment]
Unfortunately this tool only supports migrations from IIS7+, so even if you were able to complete the installation and run the tool it would immediately block on the IIS version. I'm so sorry that this limitation wasn't on the download page and I'll ask to have some notes added there so others don't have to have this experience, too.

**Comment by krolson** [comment]
(leaving open for tracking status)

**Comment by NitashaV** [comment]
We have documented this on our wiki page now at https://github.com/Azure/App-Service-Migration-Assistant/wiki.

thanks
