### ISSUE TITLE
MigCheck.exe was not found

### ISSUE THREAD

**Issue by berniethecat** [Azure/App-Service-Migration-Assistant#13]
#### Investigative information

Please provide the following:

- UTC Timestamp: 8:25 PM UTC October 1, 2019
- Migration Tool App version : Unable to determine
- OS Version: Windows 10 Enterprise

#### Repro steps

Download Azure App Service Migration Assistant and run MSI install.
Run AppServiceMigrationAssistant.exe with elevated permissions (we have an enterprise tool that controls permissions we execute applications)

#### Expected behavior

Application runs without error

#### Actual behavior

Error below in red at top. Restarting app does not help.
Migcheck.exe was not found. If this is the first time launching the Azure App Service Migration Assistant it may help to close and restart it, otherwise please use the Help menu option to report an issue.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Hello! Thank you for letting us know about this. 
I am wondering if this is an installation issue or possibly with the enterprise tool permissions integration. To start, could you please confirm that the migcheck.exe was installed on the machine? You can do this by:

- Right-click the shortcut on the desktop and choose Properties
- Copy the value from "Start in:" and look in that folder, it should be something like: C:\Users\<username>\AppData\Local\Programs\azure-appService-migrationAssistant\
- Check for a directory in that location called "migcheckbin"
- In the migcheckbin directory look for the presence of migcheck.exe

If migcheck.exe is not present, then this is a failed installation. In this case it would be awesome if you could take a look in eventvwr and let us know if you see any indications of why the install did not work correctly, as we have not seen this happening in our installations. Getting the "dir" output of the migcheckbin directory would be useful as well. But if this is an installation issue then to unblock you, it may work for you to try uninstalling AND manually deleting that C:\Users\<username>\AppData\Local\Programs\azure-appService-migrationAssistant\ directory (if needed) before re-installing (or try installing the newer Preview version).

If migcheck.exe is present in that location, I am wondering if there could be an issue with running with the enterprise tool you mention being used to control executing applications, as the App Service Migration Assistant does attempt to execute migcheck.exe from that relative location with different arguments - and perhaps the migcheck.exe and/or access to migcheck.exe needs to be somehow also specially allowed within that enterprise tool (migcheck.exe is a command line tool which reads the IIS configuration on the machine, and thus requires administrator privileges - this is why we start the AppServiceMigrationAssistant as admin).

**Comment by berniethecat** [comment]
I resolved my issue by opening a command line with elevated privileges and executing AppServiceMigrationAssistant.exe from the command line. Looks to be a blockage from our enterprise tool that controls permissions (Beyond Trust) when running from the GUI.
