### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by mrchops1024** [Azure/App-Service-Migration-Assistant#15]
#### Investigative information

Please provide the following:

- UTC Timestamp: Oct. 23 2019 23:38:30
- Migration Tool App version: 0.1.2
- OS Version: Windows Server 2012 R2 Standard

#### Repro steps

1. Download MSI
2. Install with admin priveledges on dev web server
3. Open via desktop shortcut with admin priviledges

#### Expected behavior

According to screenshots it's supposed to list my existing sites.

#### Actual behavior

Error: `TypeError: Cannot read property 'split' of undefined`

![Screen Shot 2019-10-23 at 4 42 45 PM](https://user-images.githubusercontent.com/7883662/67442102-59bd3000-f5b4-11e9-92a5-5813c480eff5.png)

#### Known workarounds

None.

**Comment by krolson** [comment]
Hello @mrchops1024,
Thank you for reporting this!

I think I know why this is happening, but to be sure it will really fix the issue you're hitting could you please do the following steps and let us know what the output looks like?

1. Find out the path for the installation of iisConfigurationHelper.exe: Right-click the AppServiceMigrationTool desktop shortcut and select Properties. Look for the path in the "Start in" value (should be something like: C:\Users\<yourUserName>\AppData\Local\Programs\azure-appService-migrationtool). 
2. Open an admin command prompt and go to that location with added "\iisConfigAssistant": C:\Users\<yourUserName>\AppData\Local\Programs\azure-appService-migrationtool\iisConfigAssistant
3. Try running this command and send us the output (obscure site names as desired): iisConfigAssistant.exe GetSiteList

Thank you,
Kristina

**Comment by mrchops1024** [comment]
I received the following error message:

```
{
  "HResult": "80070002",
  "DisplayMessage": "Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.",
  "TelemetryMessage": "An unhandled exception occurred.  HResult=80070002",
  "StackTrace": "   at iisConfigAssistant.Program.DoGetSiteList(String[] args)\r\n   at iisConfigAssistant.Program.Main(String[] args) in D:\\a\\1\\s\\src\\IisConfigurationHelper\\iisConfigAssistant\\Program.cs:line 44"
}

```

**Comment by idubnori** [comment]
I've had a same one, came from #6 
```
{
  "HResult": "80070002",
  "DisplayMessage": "Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.",
  "TelemetryMessage": "An unhandled exception occurred.  HResult=80070002",
  "StackTrace": "   at iisConfigAssistant.Program.DoGetSiteList(String[] args)\r\n   at iisConfigAssistant.Program.Main(String[] args) in D:\\a\\1\\s\\src\\IisConfigurationHelper\\iisConfigAssistant\\Program.cs:line 44"
}
```

**Comment by krolson** [comment]
Thank you for getting back to us with those details. 

We believe this is happening because the Migration Assistant has a dependency on version 4.7.2 of the .NET Framework and were able to reproduce the behavior for this reason (such as if only 4.6.1 is installed).

Can you please confirm which version(s) of the .NET Framework are installed on your machine (see https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed) and/or install 4.7.2 (possible source: https://support.microsoft.com/en-us/help/4054530/microsoft-net-framework-4-7-2-offline-installer-for-windows) and try running the tool again? 

I have opened workitems on our side to better highlight the minimum system requirements on the tool download page and the next release will be display a more informative and actionable error message.

**Comment by mrchops1024** [comment]
The server had 4.6.2 installed. I've installed 4.7.2 and verified the utility opens now.

**Comment by NitashaV** [comment]
Thanks for confirming the fix.

**Comment by RiccardoGMoschetti** [comment]
Hi,
We have some situations in which we're migrating apps hosted on W2008R2 servers with 4.6.1.
I think App Service supports this version of .Net framework. 
Would it be possible to recompile the assistant so that it is compatible with 4.6.1?
Thanks a lot.

**Comment by krolson** [comment]
(Yes. We are currently working on this for the next release.)
