### ISSUE TITLE
Config error on Windows 2008 R2 SP1

### ISSUE THREAD

**Issue by frehnejc** [Azure/App-Service-Migration-Assistant#2]
#### Investigative information
- UTC Timestamp: 1/03/2019 11:48pm
- Migration Tool App version :0.0.1.59773
- OS Version:2008 R2 Sp1 with all updates

#### Repro steps

1. Installation successful
2. Ran tool as an administrator
3. Selected simple site
4. Unable to proceed past 3 configuration errors XML excerpt below:
`{
            "CheckName": "ConfigError(/)",
            "Result": false,
            "Status": "Block",
            "Title": "Configuration Error",
            "Description": "Appears if the site contains invalid configuration.",
            "DisplayMessage": "Error parsing 'webSockets' section (hresult: 80070490), configuration path /",
            "LearnMoreLink": ""
        },
        {
            "CheckName": "ConfigError(/)",
            "Result": false,
            "Status": "Block",
            "Title": "Configuration Error",
            "Description": "Appears if the site contains invalid configuration.",
            "DisplayMessage": "Unable to read ipSecurity collection (hresult: 80004003), configuration path /",
            "LearnMoreLink": ""
        },
        {
            "CheckName": "ConfigError(Views/)",
            "Result": false,
            "Status": "Block",
            "Title": "Configuration Error",
            "Description": "Appears if the site contains invalid configuration.",
            "DisplayMessage": "Unable to read ipSecurity collection (hresult: 80004003), configuration path Views/",
            "LearnMoreLink": ""
        },`

#### Expected behaviour

After step 4 no errors received using old Migration tool and successful.

#### Actual behavior

Unable to continue to migrate.

#### Known workarounds

Unable to configure Websockets as not supported in IIS7.0, as per:
https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-websocket-protocol-support

Enabled IPSecurity by following but still error persists: 
https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/ipsecurity/

**Comment by wadeh-ms** [comment]
Thanks for the report!

The current release of the new migration tool makes some different checks to assess migration readiness from what the old tool did.  And we will be adding more checks over time (and remove some checks, as we are able to support more scenarios).

It is complicated a bit by the fact that some of the configuration parsing depends on schema that has changed a bit over time.

I will investigate these (and look for other cases) where I need to do special handling for specific IIS versions.

Thanks,
-Wade

**Comment by wadeh-ms** [comment]
I wanted to circle back on this and mention that we have an updated version of the tool at https://appmigration.microsoft.com/.

I believe that this issue is addressed in this update.  If you could please give it another try and let me know what happens, I would appreciate it.

Thanks,
-Wade
