### ISSUE TITLE
Tool fails to analyze multiple sites on consolidate server

### ISSUE THREAD

**Issue by gdiersing** [Azure/App-Service-Migration-Assistant#21]
Using the latest version 1.0.0 on Windows 2012 R2.  After installation, opened the app, and selected a site for analysis.  It’s a HelloWorld sample site, but I can recreate the error with any sites hosted.  During the analysis the tool stops reporting the following error:

We're sorry, there has been an error. To get help, please use the Help > Report Issues menu option and include the following information: Session 443e48b4-dfd4-4258-9f6e-cba2e2513f23, GETTING CONFIG: Unexpected output for GetSiteAssessmentData, error was: SyntaxError: Unexpected token { in JSON at position 256235

**Comment by fashaikh** [comment]
The error seems to match another one reported earlier.
Could you follow the instructions mentioned there:
https://github.com/Azure/App-Service-Migration-Assistant/issues/20#issuecomment-553989481

**Comment by gdiersing** [comment]
Thank you fashaikh, yes it is the same issue.  I'd previously executed iisConfigAssistant command that krolson mentioned and gotten the same experience.

**Comment by fashaikh** [comment]
We have a build that may be helpful to you.
Could you reach out to me fashaikh at microsoft dot com and I can share the fix with you

**Comment by krolson** [comment]
We believe this issue has been fixed in later releases. Please open a new issue if you are still experiencing this issue.
