### ISSUE TITLE
n: Session 58e54dc7-c890-4270-bf7e-fcf154d7bc7b. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by keithransom** [Azure/App-Service-Migration-Assistant#23]
#### Investigative information

Please provide the following:

- UTC Timestamp:
- Migration Tool App version :
- OS Version:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Thank you for reporting this, @keithransom!

Would it be possible for you to send us a copy of your anonymized configuration at appmigratetalk@microsoft.com (steps here https://github.com/Azure/App-Service-Migration-Assistant/wiki/How-the-Assistant-Works#what-information-is-sent-for-assessments to generate AnonAssessmentInfo.json)? This would allow us to get an exact repro of the issue you are hitting.

Thank you, 
Kristina

**Comment by krolson** [comment]
Hi @keithransom,
We believe that we have fixed this issue that you were running into (based on similar behavior we reproduced from info in https://github.com/Azure/App-Service-Migration-Assistant/issues/24). This was a server-side fix so you should be able to simply rerun the Assistant and get the assessment results. If you are still seeing this behavior or have any other issues please let us know!
Thanks,
Kristina
