### ISSUE TITLE
 Session c4cbdecc-a3e0-4062-b3e8-d5837ae92e38. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by deijii** [Azure/App-Service-Migration-Assistant#25]
Investigative information

Please provide the following:

    UTC Timestamp: 14:30 2020-01-08
    Migration Tool App version : Azure App Service Migration Tool V. 1.0.1
    OS Version: Windows Server 2016 Essentials

Repro steps

After I choose a site, the system cannot generate assessment report for web site. I attached the json report. Please tell me what is wrong?
AnonAssessmentInfo.json.txt
[AnonAssessmentInfo.json.txt](https://github.com/Azure/App-Service-Migration-Assistant/files/4035766/AnonAssessmentInfo.json.txt)

Provide the steps required to reproduce the problem:
Expected behavior

Provide a description of the expected behavior.
Actual behavior

Provide a description of the actual behavior observed.
Known workarounds

Provide a description of any known workarounds.

**Comment by wadeh-ms** [comment]
Hello,

This is a repro of [this issue](https://github.com/Azure/App-Service-Migration-Assistant/issues/24).  We have a fix and will be implementing it soon.

I will let you know when you can try again.

Thanks,
-Wade

**Comment by krolson** [comment]
Hello @deijii 

The fix for this issue is live, and if you try again now you should no longer see this error.

Thank you for reporting this and providing the assessment info details! Please let us know if you have any other issues or feedback about the assessment results.

-Kristina

**Comment by deijii** [comment]
I've tried it and it already works properly.

Thanks.

**Comment by wadeh-ms** [comment]
Thanks for the confirmation!

-Wade
