### ISSUE TITLE
IIS was not detected on this computer

### ISSUE THREAD

**Issue by sdabireau** [Azure/App-Service-Migration-Assistant#29]
Hello,

After starting the "Azure App Service Migration Assistant 1.0.2 (also true with 1.0.1) tool to analyse my IIS configuration the following error appears :
Error getting site list from iis configuration tool ouput: IIS was not detected on this computer

![error](https://user-images.githubusercontent.com/52539748/78066222-898e1200-7362-11ea-8de7-94c2ececcba9.jpg)

Same behavior with the commandline: iisconfigassistant.exe GetSiteList
IIS version 10.0.14393.0
4 sites, 20 AppPools and 300App
I am adminitrator of this server.

#### Investigative information

Please provide the following:

- UTC Timestamp: 15:00 2020-03-31
- Migration Tool App version : 1.0.2 (also preview and 1.0.1)
- OS Version: Windows server 2016 standard

#### Repro steps

1-Start Tool

#### Expected behavior

After starting the tool,  next step will be select the site for scan

#### Actual behavior

After starting the tool : Error getting site list from iis configuration tool ouput: IIS was not detected on this computer

#### Known workarounds
None

**Comment by wadeh-ms** [comment]
Hello,

We detect IIS by looking at the following registry key:

HKEY_LOCAL_MACHINE\Software\Microsoft\InetStp

In particular, we look at the following two DWORD32 values.  If either of them is missing or inaccessible to the Migration Assistant, then it will report that IIS was not detected:

MajorVersion
MinorVersion

-Wade

**Comment by sdabireau** [comment]
Hello Wade,
Thanks you for your reply.

it's the two registry keys:
MajorVersion: 9
MinorVersion: 0

I confirm that I have access to these two keys through my admin user.
Other facts may be without significance, we have IIS10 but majorversion is 9.

**Comment by wadeh-ms** [comment]
Ok.  I can reproduce the error with MajorVersion set to 9.

Please go ahead and change it to 10.  Do you have any idea how that value was set to 9?  This had to be done either manually, or by some code that is not IIS.

-Wade

**Comment by sdabireau** [comment]
Thanks you, the tool scanning (when majoversion set to 10) !
