### ISSUE TITLE
Unable to proceed (Next) past Login to Azure after devicelogin

### ISSUE THREAD

**Issue by skeeler** [Azure/App-Service-Migration-Assistant#30]
Running the App Migration tool locally, discovered a web app (IIS) and resolved all Errors, allowing me to progress to the "Login to Azure" step. I then authenticate successfully (using https://microsoft.com/DeviceLogin) and close the browser window as instructed. At this point, the "Next" button in the App Migration tool is not enabled, and I cannot proceed any further in the process.

#### Investigative information

Please provide the following:

- UTC Timestamp: 6:30 PM UTC
- Migration Tool App version : 1.0.2
- OS Version: Windows Server, version 1809

#### Repro steps

Provide the steps required to reproduce the problem:
1. Install the App Migration tool locally
2. Run tool
3. Select web app to assess and run assessment
4. Click "Next"
5. Authenticate with Azure via https://microsoft.com/DeviceLogin
6. After authentication, the "Next" button on this page is NOT ENABLED

#### Expected behavior

Provide a description of the expected behavior.

After I authenticate, the "Next" button on the "Login to Azure" page should be enabled.

#### Actual behavior

Provide a description of the actual behavior observed.

After I authenticate, the "Next" button on the "Login to Azure" page IS NOT enabled, blocking further progress.

#### Known workarounds

Provide a description of any known workarounds.

N/A

**Comment by krolson** [comment]
Thank you for reporting this - we haven't seen this behavior previously. Couple questions to try to figure this out:

- Does this happen consistently every time or intermittently when you try to login? 
- What message do you see when you have completed the authentication step in the browser? (Does it say "You have signed in to the Azure App Service Migration Assistant application on your device. You may now close this window." or something different?)
- About what length of time was it between having logged in successfully and the Next button still being disabled in the Migration Assistant application (i.e. was this a matter of less than a minute, more than a minute)? 
- Did you have anonymous logging enabled / could you try doing this again with logging enabled to see if there are any error traces that we could look at in this case? I didn't notice any telemetry around this noted time.

Sorry you're running into this and hope we can figure it out.

**Comment by TomaszWRutkowski** [comment]
Had the same problem with this Tool when tried to log into Azure with account with MFA (Authenticator App) enabled. 

Next was greyed out and unavailable + no notification on Authenticator App 

Workaround for me was to create an additional account without MFA. Tool run with this account correctly and I was able to move to another section.

**Comment by krolson** [comment]
Thank you @skeeler for reporting this issue and @TomaszWRutkowski for the workaround you used - possibly this is some issue with using device code authentication and some MFA setups (I know it is not universal, which can make it harder to pin down - my primary account uses MFA including with Authenticator App and has not had this issue). We will keep an eye out for this type of behavior going forward - closing this issue for now due to lack of recent activity - if others are encountering this please do feel free to open a new issue to get our attention and add any additional details of your type of account/auth setup to help pin-down or rule out the MFA angle here!
