### ISSUE TITLE
App Migration Assistant Installer not launching

### ISSUE THREAD

**Issue by charlieswing** [Azure/App-Service-Migration-Assistant#32]
I have downloaded the App Service Migration Assistant installer. When I launch the installer, a "Please wait..." status message pops up quickly then goes away. After this, no other windows open showing any installation of this program. I have tried this several times. Is this a known issue? Running on Windows 10.

**Comment by krolson** [comment]
Even in a successful install, there unfortunately isn't great feedback that installation is complete. If everything worked as it should, the main indicator would be a shortcut on your desktop labeled AppServiceMigrationAssistant and the bits would be installed at %localappdata%\Programs\azure-appService-migrationAssistant

If the above didn't happen then there might be an indicator of why in Event Viewer (click Windows key and search for that name) in the recent Windows Logs > Application events. 

Please let me know if the bits were installed or if you see anything in the Event Viewer logs about it after an unsuccessful install.

**Comment by charlieswing** [comment]
Thanks for the quick reply! You're correct....it added a shortcut to my desktop after sometime. Closing issue.
