### ISSUE TITLE
Cannot move past assessment report 

### ISSUE THREAD

**Issue by mookiejones** [Azure/App-Service-Migration-Assistant#34]
#### Investigative information

Please provide the following:

- UTC Timestamp:
- Migration Tool App version :1.0.6
- OS Version: Windows Server 2008 R2 Standard

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

I have run the tool and fixed any issues that it has flagged, but it ends with an error of session timed out.
is there way of modifying this?

**Comment by krolson** [comment]
Thanks for letting us know about this.

To clarify, it sounds as though you have gotten assessment results back at some point (that you see issues that were flagged), but also that a session times out - are these happening in the same run of the tool or started after you fixed the flagged issues? Do you see specific results on the Assessment Report page before this happens? Do you see the "Next" button enabled or disabled? Does the session time out error occur on the Assessment Report page or after clicking Next?

If this Next button is not enabled or this happens before clicking Next on the Assessment Report page, it would help us isolate the problem if you could do the steps outlined here to generate the anonymous configuration file using the command line: 
https://github.com/Azure/App-Service-Migration-Assistant/wiki/How-the-Assistant-Works#what-information-is-sent-for-assessments

Please let us know if you run into any issues with doing the above steps, and/or if it completes if it takes a notable amount of time or the file size of the generated assessment. Also, if you could confirm you have left logging enabled and provide a timestamp of about when you ran into this issue we may be able to find more information there. 

Thank you.

**Comment by mookiejones** [comment]
So the error appears after ive fixed all of the issues. Theres are no results shown nor any info shown other than the timeout. the next button is disabled. 

The Timeout occurs during the assessment report.

**Comment by mookiejones** [comment]
[AnonAssessmentInfo.txt](https://github.com/Azure/App-Service-Migration-Assistant/files/5017081/AnonAssessmentInfo.txt)

**Comment by krolson** [comment]
Worked with this user on separate channel to do do manual workaround for the migration. Also this issue may be fixed in latest 1.0.8 release. If you see an issue like this using v1.0.8 or greater please let us know by opening a new issue.
