### ISSUE TITLE
Error occurred: "Too many instances of <Connector> element"

### ISSUE THREAD

**Issue by PerumalsamyP-Hexaware** [Azure/App-Service-Migration-Assistant#40]
I am getting the error message like Error occurred: "Too many instances of <Connector> element" in choose a site page after selecting Tomcat Server radio button. please help me to resolve this issue to select a site.

#### Investigative information

Please provide the following:

- UTC Timestamp: 06:14:11 UTC
- Migration Tool App version : 1.0.8.0
- OS Version: Windows 10 Enterprise

#### Repro steps

Provide the steps required to reproduce the problem:

Step 1: Open the Azure app service migration assistant tool
Step 2: select the server type is Tomcat Server

#### Expected behavior

After I perform step 2 the actual list of sites should be listed.

#### Actual behavior

Step 2 actually giving an error - (Error occurred: "Too many instances of <Connector> element") and zero sites found.

#### Known workarounds

List of sites should be shown to see an assessment 

![azureappservice](https://user-images.githubusercontent.com/68582721/94397410-61e8fc80-0181-11eb-9165-6dad2c4aa74a.PNG)

**Comment by krolson** [comment]
Hello @PerumalsamyP-Hexaware - thank you for letting us know this doesn't work for you. I'm afraid the Preview version only works with very simple single-connector configurations. 
If you would like to try doing a migration outside of the tool, there are some instructions for how to do this here: https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-tomcat-to-tomcat-app-service.
If you're creating the App Service site in the portal (portal.azure.com) you would create a new App Service app that is a Linux site with the "Code" (as opposed to Docker Container) option, choosing a close-matching Java Tomcat option for the Runtime stack. Then after the site is created you would push a .war file with your content, such as using a curl command as outlined here: https://docs.microsoft.com/en-us/azure/app-service/deploy-zip#with-curl
If you have any trouble with these steps please let us know.

**Comment by PerumalsamyP-Hexaware** [comment]
Hello @krolson - thank you for your comments and the issue got fixed after changing to single port configuration in server.xml file.
