### ISSUE TITLE
Give option to allow multiple site assessment in single tool or different instance of the tool

### ISSUE THREAD

**Issue by prasanadas** [Azure/App-Service-Migration-Assistant#42]
#### Investigative information

Please provide the following:

- UTC Timestamp:
- Migration Tool App version :
- OS Version:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Thanks for letting us know you'd like to see this. We do have this in our backlog to add as a feature - I've added the "enhancement" label here for tracking.

**Comment by prasanadas** [comment]
Thanks krolson for your reply.
I am going through one of your video ....https://www.youtube.com/watch?v=Smgxp6bb5lw
Explained nicely.
Can you let us know how can we install and run this tool using command prompt for Windows.
Sharing link will be helpful. Will wait for your reply.

**Comment by krolson** [comment]
The option to assess all sites on an IIS server at one time is now possible using the PowerShell scripts option - this is a lightweight option that involves simply dropping a directory of scripts on the machine and running the first one (Get-SiteReadiness.ps1) to get assessment details for all the sites. 
Main info page: https://github.com/Azure/App-Service-Migration-Assistant/wiki/PowerShell-Scripts
Place to download: https://azure.microsoft.com/en-us/services/app-service/migration-assistant/
