### ISSUE TITLE
Error while migrating Java application from Linux 

### ISSUE THREAD

**Issue by RavishankarST-Hexaware** [Azure/App-Service-Migration-Assistant#46]
#### Investigative information

Please provide the following:

- UTC Timestamp: 09:28:00:0000
- Migration Tool App version :1.0.8
- OS Version: CentOS 7

#### Repro steps

Provide the steps required to reproduce the problem:

Trying to migrate a Java application, while migration we get the following error in the log

LOG: Azure Options info Starting ZipDeploy content publish {​​​​​}​​​​​
LOG: Azure Options error Migration Step Error {​​​​​"stepGroup":"CONTENT_PUBLISH","stepName":"Publish site content","message":"404 - \"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.\""}​​​​​
LOG: Azure Options error AZMigrate Step Error {​​​​​"stepGroup":"AZMIGRATE_MIGRATION_SEND","stepName":"Sending migration progress data for site content publishing","message":"StatusCodeError: 404 - \"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.\""}​​​​​
LOG: Azure Options error Error during ZipDeploy content publish {​​​​​"message":"404 - \"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.\""}​​​​​
LOG: Azure Options error PublishSiteContent failure {​​​​​"message":"specific error should be logged in another event"}​​​​​

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Hello @RavishankarST-Hexaware - this sounds like an issue that was fixed in a targeted rerelease of the Linux preview. The current version of the Linux Preview available for download is 1.0.9 - could you please try using this version and confirm if that resolves this issue for you?

**Comment by RavishankarST-Hexaware** [comment]
Yes 1.0.9 fixed the issue.

Thanks

**Comment by RavishankarST-Hexaware** [comment]
Issues resolved
