### ISSUE TITLE
Session e9e156ed-5dfe-424c-86bf-2fd4234bebc4 - Unable to complete online assessment

### ISSUE THREAD

**Issue by nhoeppner007** [Azure/App-Service-Migration-Assistant#52]
Ran App Service tool on a VM in Azure Government. Errors immediately with Unable to complete online assessment; this may indicate blocks on outbound connections. Disabled Windows Defender Firewall. No blocks on vNet NSG. Ran Wireshark trace and didn't find any errors on blocks to any of the URLs.

Session e9e156ed-5dfe-424c-86bf-2fd4234bebc4

#### Investigative information

Please provide the following:

- UTC Timestamp:
- Migration Tool App version : 1.0.6
- OS Version: Windows Server 2016

#### Repro steps

Provide the steps required to reproduce the problem:

Opened App Service Migration Assistant and selected Default Web Site. It errors out immediately.

#### Expected behavior

Provide a description of the expected behavior.

 We're sorry, there has been an error. To get help, please use the Help > Report Issues menu option and include the following information: Session e9e156ed-5dfe-424c-86bf-2fd4234bebc4. Unable to complete online assessment; this may indicate blocks on outbound connections. Please see this page https://go.microsoft.com/fwlink/?linkid=2112618 for more information on what outbound connections must be allowed. https://go.microsoft.com/fwlink/?linkid=2112618

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Hello @nhoeppner007 - I am sorry to hear you are running into this. The outbound connection that is needed for the assessment to complete is to this endpoint: readinessapi.trafficmanager.net, and the error behavior is consistent with network blocking the request. Could you confirm if you are able to reach "readinessapi.trafficmanager.net" in a browser on that machine (it should just show a generic "Your Functions 3.0 app is up and running" page if it works)? That can sometimes be a quick way to tell if it is blocked (though the converse is not true for if it works) - I am hoping that this might just be an outbound network restriction at some other less obvious level than the Windows Defender Firewall.

**Comment by nhoeppner007** [comment]
Hi @krolson. I'm able to resolve the URL fine. We have a proxy that we use that could possibly be restricting something, however, when running a trace it didn't error out with anything from the proxy.  I'll reach out to our l3 network team to see if they see any activity.

**Comment by krolson** [comment]
An alternative option now would be to try using the PowerShell scripts that were recently released - these do not require outbound connectivity to do the assessment step (and will assess all sites on the server at once) - the scripts are a lightweight option that involves simply dropping a directory of scripts on the machine (or at least a machine-accessible location) in order to try it out.

Main info page: https://github.com/Azure/App-Service-Migration-Assistant/wiki/PowerShell-Scripts
Place to download: https://azure.microsoft.com/en-us/services/app-service/migration-assistant/
