### ISSUE TITLE
Session 20e69f70-9015-4aaf-bd26-8277a02e59eb. CONNECTION STRING CHECKS

### ISSUE THREAD

**Issue by fdeenik** [Azure/App-Service-Migration-Assistant#53]
I have run the  Azure App Service Migration Assistant om a IIS website. During the assesment the following error occured:
`Session 20e69f70-9015-4aaf-bd26-8277a02e59eb. CONNECTION STRING CHECKS: Error converting value 22-9-2020 16:51:10 to type 'iisConfigHelper.AnonymousString'. Path 'appSettings[18].value', line 2889, position 48.
`This seems to be related to the following line in the web.config:
`<add key="zs-component-servicesRestart" value="2020-09-22T16:51:10" />`
Which is part of the `<configuration><appSettings>` section. If this line is commented out the assistant runs without ant issues.

#### Investigative information

- UTC Timestamp: 3-18-2021 9:25
- Migration Tool App version : 1.0.6
- OS Version: Windows Server 2016 (10.0.14393)

#### Repro steps

1. Start the Azure App Service Migration Assistant
2. Select the IIS Site
3. Click: Next
4. After the assessment the error is shown

#### Expected behavior

The assessment wizard is expected to complete without errors.

#### Actual behavior

The assessment wizard shows the following error: `We're sorry, there has been an error. To get help, please use the Help > Report Issues menu option and include the following information: Session 88ed3255-8a9b-4e44-9a98-48d1eca0ed7a. CONNECTION STRING CHECKS: Error converting value 22-9-2020 16:51:10 to type 'iisConfigHelper.AnonymousString'. Path 'appSettings[18].value', line 2889, position 48.`

#### Known workarounds

Remove the following line from the web.config: `<add key="zs-component-servicesRestart" value="2020-09-22T16:51:10" />`

**Comment by krolson** [comment]
Hi @fdeenik - thank you so much for reporting this issue! This is a bug in the 1.0.6 version of the Migration Assistant. I am glad you were able to find a way to work around it, and will note for others or if you have additional migrations pending that I believe this particular scenario is already unblocked in the Preview (1.0.8 version) of the Migration Assistant, available at https://azure.microsoft.com/en-us/services/app-service/migration-assistant/.

**Comment by fdeenik** [comment]
Hi @krolson, I can confirm that version 1.0.8 works as expected without the workaround.
