### ISSUE TITLE
Session 30843b79-8fa6-457f-885b-aaa7031fb4f8. Failed request to assessment endpoint with status code 403

### ISSUE THREAD

**Issue by DGrahamP** [Azure/App-Service-Migration-Assistant#69]
Running Azure App Service Migration Wizard 1.0.6 locally on server as admin.  Sites are detected, assessment report worked once, but then fails with error in title.

Auth on Site is set to Anonymous

**Comment by krolson** [comment]
Hi @DGrahamP,

Thanks for reporting this behavior. I'm not seeing a generic issue with the assessment backend being inaccessible. I'm curious - if you close and reopen the Migration Assistant does it work the first time or still fail every time? If you try to reach http://readinessapi.trafficmanager.net/ in a browser does it also return a 403?

The server-side logs for the readiness API don't record these 403s, which makes me suspect the request might be getting blocked in a layer somewhere above the assessment endpoint.

If this is persistent you also have the option of using the PowerShell scripts to get the assessment results in a json block for all the sites on the server at once without reaching out to the assessment endpoint ([more info](https://github.com/Azure/App-Service-Migration-Assistant/wiki/PowerShell-Scripts)).
