### ISSUE TITLE
Java Tomcat sites missing in Migration assistant

### ISSUE THREAD

**Issue by karthikaditya** [Azure/App-Service-Migration-Assistant#70]
#### Investigative information

Please provide the following:

- UTC Timestamp: 2022-08-26T08:50:18Z
- Migration Tool App version : 1.0.8
- OS Version: Edition	Windows Server 2022 Datacenter Azure Edition

I am trying to migrate a Java web app running on a local Tomcat server to an Azure web app using the Migration assistant. I have set the JAVA_HOME and CATALINA_HOME environment variables required by the assistant.

#### Expected behavior

I would like to see all of the applications/sites that are running on Tomcat server to appear in the Migration assistant

#### Actual behavior

However, I only see some of the sites running on Tomcat and not all of them. Please see below images for reference.
Why are the "SampleWebApp" and "MyWebApp2" applications not available for selection in the Migration tool?

<img width="703" alt="migration_asst_java-sites" src="https://user-images.githubusercontent.com/16631223/186867470-7273a745-0d55-480c-ac57-4d1d92213abb.PNG">

<img width="829" alt="tomcat_app_list" src="https://user-images.githubusercontent.com/16631223/186867522-b96a8210-c7de-4531-9a1e-795627579ab8.PNG">

![image](https://user-images.githubusercontent.com/16631223/186867913-8913dd51-91d2-48aa-9486-2810d16c6a1a.png)

**Comment by krolson** [comment]
Hi @karthikaditya,

The tooling is generating this list of applications in 2 ways: 
1. It looks for .war files under CATALINA_HOME\\[appBase] directory (the appBase location is defined in the CATALINA_HOME\conf\server.xml file - by default this path will look something like: "C:\Program Files (x86)\Apache Software Foundation\Tomcat 8.5\webapps" - i.e. CATALINA_HOME\webapps)
2. It looks for directories under CATALINA_HOME\\[appBase] path that contain a web.xml file (this will often be in a WEB-INF\web.xml location in the app)

If we're not finding your applications then either we're missing a case we should be including in the app discovery and/or there's a bug in how we're finding them. It would help us figure this out if you could share the path information for either SampleWebApp or MyWebApp2 - as in: if it's a .war file what does the path look like for the .war file, and if it is an unpackaged directory, what does the path to the web.xml look like?

Also, just to rule it out, could you confirm that the CATALINA_HOME path is not being set at a user level that might override the value you're expecting?

Thank you for your help and reporting this!

**Comment by karthikaditya** [comment]
Hi @krolson,

The 2 missing applications were located in a folder called "wtpwebapps" i.e. CATALINA_HOME\wtpwebapps.

Once I created their WAR files in the CATALINA_HOME\webapps folder, they appeared in the Migration tool list, and I was able to proceed with the next steps.

Thank you for the clarifications.
