### ISSUE TITLE
Session 2cc14f4a-95a8-4b8b-baf2-f7aa133987df. timed out

### ISSUE THREAD

**Issue by avjabalpur** [Azure/App-Service-Migration-Assistant#80]
#### Investigative information

Please provide the following:

- UTC Timestamp:
- Migration Tool App version :
- OS Version:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by krolson** [comment]
Hi @avjabalpur - apologies for the delayed response - at what step is this timeout happening? And could you confirm if you're using the 1.0.6 or 1.0.9 Preview version of the tool? 

The PowerShell migration scripts could be an option to evaluate and migrate this site instead, as it has some optimizations that should make the assessment step much quicker. The scripts are available on http://aka.ms/appmigrate ("App Service migration assistant for PowerShell scripts") - notes on how to use them are here: https://github.com/Azure/App-Service-Migration-Assistant/wiki/PowerShell-Scripts

Closing this now for not being actionable without more detail, please open a new issue if you are still seeing this or have issues with the PS scripts.
